### PR TITLE
convert competition to article

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@KaitCrawford @saeedmb8 @codiebeulaine review please

**Comment by miltontony** [comment]
Tests are failing because we need to pin `django-compressor==1.5` they released 1.6 which is breaking at the moment :(

**Comment by codiebeulaine** [comment]
@miltontony the title and body are not the only things that can pre-populate the article page. The username/anonymous might be good as well?

**Comment by codiebeulaine** [comment]
@miltontony awesome! :+1:

**Comment by smarzban** [comment]
\o/ :tada:

**Pull request merged**
