### PR TITLE
Add terms and conditions and thank you page to models

### PR DESCRIPTION
**Pull request by smarzban**

### CODE REVIEW

**Comment by miltontony** [comment]
:+1: 
Just a note that for the Thank You page, you should find a way of having a default thank you page. Tamsen doesn't want to have to create a thank you page for every competition.

**Comment by smarzban** [comment]
@miltontony ready for review, regards with Thank You page, yes I saw that in the SoW so my plan Is to have it define in the template like this:

```
{% if self.title %}
  <h3>{{self.title}}</h3>
{% else %}
  <h3>Thank you for sharing your story</h3>
{% endif %}

{% if self.subtitle %}
  <p>2{{self.subtitle}}</p>
{% else %}
  <p> Thank you message </p>
{% endif %}
```

This way there will be a default thank you messages and if they want to change it one day they can. And we can use the function get_parent_page in the template as well

**Comment by smarzban** [comment]
@miltontony ready for review

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
